snowflake_profile:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ca04050.ap_south_1.aws
      user: milindraut
      password: Jijaraut@19062021
      role: ACCOUNTADMIN
      database: DEMO_DB
      warehouse: COMPUTE_WH
      schema: STG